[versions]
agp = "8.5.2"
itext7Core = "7.2.5"
jbcrypt = "0.4"
jtds = "1.3.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.1"
constraintlayout = "2.1.4"
bouncycastle = "1.70"
smbj = "0.11.5"
retrofit = "2.9.0"
gson = "2.10.1"
camerax_version = "1.4.1"
zxing-core = "3.5.1"
zxing-android-embedded = "4.3.0"
rxjava = "3.1.7"
rxandroid = "3.0.2"
paging = "3.1.0"  # Versi terbaru Paging 3
recyclerview = "1.2.1"  # Versi terbaru RecyclerView
java_websocket = "1.5.2"
swiperefresh = "1.1.0"






[libraries]
itext7-core = { module = "com.itextpdf:itext7-core", version.ref = "itext7Core" }
jbcrypt = { module = "org.mindrot:jbcrypt", version.ref = "jbcrypt" }
jtds = { module = "net.sourceforge.jtds:jtds", version.ref = "jtds" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
smbj = { group = "com.hierynomus", name = "smbj", version.ref = "smbj" }
bouncycastle = { group = "org.bouncycastle", name = "bcprov-jdk15on", version.ref = "bouncycastle" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax_version" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax_version" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax_version" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax_version" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing-core" }
zxing-android-embedded = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxing-android-embedded" }
rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
rxandroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxandroid" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "java_websocket" }
swiperefresh = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefresh" }







[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }